# Generated by Django 5.2.12 on 2026-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.IntegerField(default=240),
        ),
    ]
