# Generated by Django 5.2.12 on 2026-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_credits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credits",
            field=models.IntegerField(default=0),
        ),
    ]
