# Generated by Django 5.2.12 on 2026-03-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(blank=True, default="", max_length=42),
        ),
        migrations.AddField(
            model_name="user",
            name="wallet_private_key",
            field=models.CharField(blank=True, default="", max_length=66),
        ),
    ]
