# Generated by Django 5.2.12 on 2026-03-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('order_id', models.CharField(blank=True, max_length=200)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
            },
        ),
    ]
