# Generated by Django 5.2.12 on 2026-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credittransaction",
            name="tx_hash",
            field=models.CharField(blank=True, default="", max_length=66),
        ),
        migrations.AddField(
            model_name="sale",
            name="tx_hash",
            field=models.CharField(blank=True, default="", max_length=66),
        ),
    ]
